require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TakeoffsController do

  # This should return the minimal set of attributes required to create a valid
  # Takeoff. As you add validations to Takeoff, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TakeoffsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all takeoffs as @takeoffs" do
      takeoff = Takeoff.create! valid_attributes
      get :index, {}, valid_session
      assigns(:takeoffs).should eq([takeoff])
    end
  end

  describe "GET show" do
    it "assigns the requested takeoff as @takeoff" do
      takeoff = Takeoff.create! valid_attributes
      get :show, {:id => takeoff.to_param}, valid_session
      assigns(:takeoff).should eq(takeoff)
    end
  end

  describe "GET new" do
    it "assigns a new takeoff as @takeoff" do
      get :new, {}, valid_session
      assigns(:takeoff).should be_a_new(Takeoff)
    end
  end

  describe "GET edit" do
    it "assigns the requested takeoff as @takeoff" do
      takeoff = Takeoff.create! valid_attributes
      get :edit, {:id => takeoff.to_param}, valid_session
      assigns(:takeoff).should eq(takeoff)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Takeoff" do
        expect {
          post :create, {:takeoff => valid_attributes}, valid_session
        }.to change(Takeoff, :count).by(1)
      end

      it "assigns a newly created takeoff as @takeoff" do
        post :create, {:takeoff => valid_attributes}, valid_session
        assigns(:takeoff).should be_a(Takeoff)
        assigns(:takeoff).should be_persisted
      end

      it "redirects to the created takeoff" do
        post :create, {:takeoff => valid_attributes}, valid_session
        response.should redirect_to(Takeoff.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved takeoff as @takeoff" do
        # Trigger the behavior that occurs when invalid params are submitted
        Takeoff.any_instance.stub(:save).and_return(false)
        post :create, {:takeoff => {}}, valid_session
        assigns(:takeoff).should be_a_new(Takeoff)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Takeoff.any_instance.stub(:save).and_return(false)
        post :create, {:takeoff => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested takeoff" do
        takeoff = Takeoff.create! valid_attributes
        # Assuming there are no other takeoffs in the database, this
        # specifies that the Takeoff created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Takeoff.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => takeoff.to_param, :takeoff => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested takeoff as @takeoff" do
        takeoff = Takeoff.create! valid_attributes
        put :update, {:id => takeoff.to_param, :takeoff => valid_attributes}, valid_session
        assigns(:takeoff).should eq(takeoff)
      end

      it "redirects to the takeoff" do
        takeoff = Takeoff.create! valid_attributes
        put :update, {:id => takeoff.to_param, :takeoff => valid_attributes}, valid_session
        response.should redirect_to(takeoff)
      end
    end

    describe "with invalid params" do
      it "assigns the takeoff as @takeoff" do
        takeoff = Takeoff.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Takeoff.any_instance.stub(:save).and_return(false)
        put :update, {:id => takeoff.to_param, :takeoff => {}}, valid_session
        assigns(:takeoff).should eq(takeoff)
      end

      it "re-renders the 'edit' template" do
        takeoff = Takeoff.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Takeoff.any_instance.stub(:save).and_return(false)
        put :update, {:id => takeoff.to_param, :takeoff => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested takeoff" do
      takeoff = Takeoff.create! valid_attributes
      expect {
        delete :destroy, {:id => takeoff.to_param}, valid_session
      }.to change(Takeoff, :count).by(-1)
    end

    it "redirects to the takeoffs list" do
      takeoff = Takeoff.create! valid_attributes
      delete :destroy, {:id => takeoff.to_param}, valid_session
      response.should redirect_to(takeoffs_url)
    end
  end

end
